    <url>
        <loc>@{siteAddress}/Arcadia/</loc>
        <lastmod>2026-01-01</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.3</priority>
    </url>
    <url>
        <loc>@{siteAddress}/Arcadia/Ring1/</loc>
        <lastmod>2026-01-01</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.3</priority>
    </url>
    <url>
        <loc>@{siteAddress}/Arcadia/Ring2/</loc>
        <lastmod>2026-01-01</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.3</priority>
    </url>
    <url>
        <loc>@{siteAddress}/Arcadia/ARMS/</loc>
        <lastmod>2026-01-01</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.3</priority>
    </url>
    <url>
        <loc>@{siteAddress}/Arcadia/Engine/</loc>
        <lastmod>2026-01-01</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.3</priority>
    </url>
    <url>
        <loc>@{siteAddress}/Arcadia/news</loc>
        <lastmod>2026-01-01</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.3</priority>
    </url>
    <url>
        <loc>@{siteAddress}/Arcadia/roadmap</loc>
        <lastmod>2026-01-01</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.3</priority>
    </url>
    <url>
        <loc>@{siteAddress}/Arcadia/roadmap-archive</loc>
        <lastmod>2026-01-01</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.3</priority>
    </url>
